spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.json.use.type.headers: false
      spring.json.value.default.type: com.example.demo.User
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

